apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oev21nay2-nodejs
  janus-idp.io/tekton: oev21nay2-nodejs
  backstage.io/kubernetes-id: oev21nay2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oev21nay2-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
